//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int ID { get; set; }
        public string StudentName { get; set; }
        public int Language_Arts { get; set; }
        public int Science { get; set; }
        public int SocialStudies { get; set; }
        public int Math { get; set; }
    }
}
